print ('Python CLI Reddit Browser Command Menu:\n')
print ('All commands must end with the proper file extension or else they will not run. For example, to run the help command, you can do "help.py".\n')
print ('Commands:\n')
print ('help.py - Prints a list of commands for the browser.')
print ('credits.py - Prints the credits for this project.')
print ('getImageFromUrl.py - Prints the image out in the command line. This function isnt fully functional and will be improved on later.')
print ('getRedditPostLinks.py - Returns a list of reddit post links from a specific page.')
print ('getPostData.py - Returns the data about a specific post (the content, upvotes, author, etc.).')